#pragma once

#include <X11/XKBlib.h>
#include <X11/XF86keysym.h>

static constexpr auto MOD1_KEY { Mod1Mask };
static constexpr auto MOD4_KEY { Mod4Mask };
static constexpr auto CTRL_KEY { ControlMask };
static constexpr auto SHIFT_KEY { ShiftMask };

enum class Key {
  Esc       = XK_Escape,
  F1        = XK_F1,
  F2        = XK_F2,
  F3        = XK_F3,
  F4        = XK_F4,
  F5        = XK_F5,
  F6        = XK_F6,
  F7        = XK_F7,
  F8        = XK_F8,
  F9        = XK_F9,
  F10       = XK_F10,
  F11       = XK_F11,
  F12       = XK_F12,
  Numlock   = XK_Num_Lock, 
  Gr        = XK_grave,
  N1        = XK_1,
  N2        = XK_2,
  N3        = XK_3,
  N4        = XK_4,
  N5        = XK_5,
  N6        = XK_6,
  N7        = XK_7,
  N8        = XK_8,
  N9        = XK_9,
  N0        = XK_0,
  Minus     = XK_minus,
  Equal     = XK_equal,
  Backspace = XK_BackSpace,
  Tab       = XK_Tab,
  Q         = XK_q,
  W         = XK_w,
  E         = XK_e,
  R         = XK_r,
  T         = XK_t,
  Y         = XK_y,
  U         = XK_u,
  I         = XK_t,
  O         = XK_o,
  P         = XK_p,
  Bleft     = XK_bracketleft,
  Bright    = XK_bracketright,
  A         = XK_a,
  S         = XK_s,
  D         = XK_d,
  F         = XK_f,
  G         = XK_g,
  H         = XK_h,
  J         = XK_j,
  K         = XK_k,
  L         = XK_l,
  Z         = XK_z,
  X         = XK_x,
  C         = XK_c,
  V         = XK_v,
  B         = XK_b,
  N         = XK_n,
  M         = XK_m,
  Comma     = XK_comma,
  Period    = XK_period,
  Space     = XK_space,
  Left      = XK_Left,
  Up        = XK_Up,
  Down      = XK_Down,
  Right     = XK_Right,
  Return    = XK_Return,
  Sleep     = XF86XK_Sleep,
};
